name: Surgie's Gaming Notes
title: Surgie's Gaming Notes
markdown: kramdown
permalink: pretty
defaults:
  scope:
    path: ""
    type: "pages"
  values:
    layout: "default"
  scope:
    path: "_posts"
  values:
    layout: "post"
